# Contributors' Guide

In this guide, we collect useful information for authors and contributors to the book.

## Local rendering instructions

By default, the book is rendered automatically through GitHub actions when you merge to `main`. However, if you want to preview the book locally, you can do so by following these instructions:

1. Clone [the repo](https://github.com/pat-alt/julia-deeplearning-book) for this book
   somewhere on your computer. Navigate using a terminal to the folder containing
   the repository.
2. Add the Julia kernel to Jupyter. This is currently tested with Julia 1.9,
   your results may vary with different versions of julia.

	```julia
	# Load the current environment
	using Pkg; Pkg.activate("."); Pkg.instantiate()

	# Import IJulia
	using IJulia

	# Call a notebook. You can close it once you call this --
	# we only need to run notebook() once for it to build the
	# jupyter kernel for Julia.
	notebook()
	```

::: {.callout-tip}
## Troubleshooting

If you get an error message about `jupyter` not being found, you may need to `build IJulia` first. This 
:::

3. Install [Quarto](https://quarto.org/docs/get-started/).
4. Render the website from the root of this folder with 

	```
	quarto render
	```
5. Optionally, if you want to preview the HTML version of the page 
   before you merge it to `main`, you can run

	```
	quarter preview
	```